$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$CodexRoot = Join-Path $env:USERPROFILE ".codex"
$Summary = [ordered]@{
  timestamp = (Get-Date).ToString("o")
  filesCopied = 0
  warnings = @()
  sources = @()
}

function Ensure-Dir {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
  }
}

function Get-SafeRelativePath {
  param([string]$BasePath, [string]$FullPath)
  $base = (Resolve-Path -LiteralPath $BasePath).Path.TrimEnd("\")
  $full = (Resolve-Path -LiteralPath $FullPath).Path
  if ($full.StartsWith($base, [System.StringComparison]::OrdinalIgnoreCase)) {
    return $full.Substring($base.Length).TrimStart("\")
  }
  return $full
}

function Remove-GeneratedFolder {
  param([string]$RelativePath)
  $target = Join-Path $RepoRoot $RelativePath
  if (Test-Path -LiteralPath $target) {
    Remove-Item -LiteralPath $target -Recurse -Force
  }
  Ensure-Dir $target
}

function Copy-IfExists {
  param([string]$Source, [string]$Destination)
  if (Test-Path -LiteralPath $Source -PathType Leaf) {
    Ensure-Dir (Split-Path -Parent $Destination)
    Copy-Item -LiteralPath $Source -Destination $Destination -Force
    $script:Summary.filesCopied++
  }
}

function Copy-Pattern {
  param([string]$SourceRoot, [string]$DestinationRoot, [string]$RelativePattern)
  $base = Split-Path -Parent $RelativePattern
  $leaf = Split-Path -Leaf $RelativePattern
  $sourceDir = if ($base -and $base -ne ".") { Join-Path $SourceRoot $base } else { $SourceRoot }
  if (-not (Test-Path -LiteralPath $sourceDir)) { return }
  Get-ChildItem -LiteralPath $sourceDir -Filter $leaf -File -Force -ErrorAction SilentlyContinue | ForEach-Object {
    $relative = Get-SafeRelativePath $SourceRoot $_.FullName
    Copy-IfExists $_.FullName (Join-Path $DestinationRoot $relative)
  }
}

function Export-System {
  param([string]$Name, [string]$Source, [string]$DestinationRelative)
  $dest = Join-Path $RepoRoot $DestinationRelative
  Remove-GeneratedFolder $DestinationRelative
  if (-not (Test-Path -LiteralPath $Source)) {
    $script:Summary.warnings += "Missing source: $Source"
    return
  }

  $script:Summary.sources += [ordered]@{ name = $Name; source = $Source; destination = $DestinationRelative }

  @(
    "README.md",
    "safety-policy.md",
    "workflow-policy.md",
    "tool-selection-policy.md",
    "capability-gap-radar.md",
    "manual-auth-needed.md",
    "improvement-notes.md",
    "tools/*.mjs",
    "tools/*.js",
    "tools/*.sh",
    "tools/package.json",
    "templates/*.md",
    "skill-prompts/*.md",
    "knowledge/*.md",
    "knowledge/*.json",
    "knowledge/capability-orchestration/*.md",
    "knowledge/routing/*.md",
    "knowledge/color/*.md",
    "knowledge/spacing/*.md",
    "knowledge/typography/*.md",
    "knowledge/layout/*.md",
    "knowledge/motion/*.md",
    "knowledge/components/*.md",
    "knowledge/inspection/*.md",
    "knowledge/verification/*.md",
    "knowledge/api/*.md",
    "knowledge/database/*.md",
    "knowledge/vps/*.md",
    "learning/error-patterns.md",
    "learning/routing-lessons.md",
    "learning/tool-failure-patterns.md",
    "learning/verification-mistakes.md",
    "learning/skill-update-candidates.md",
    "learning/resolved-lessons.md",
    "learning/learning-policy.md"
  ) | ForEach-Object { Copy-Pattern $Source $dest $_ }

  $summaryPath = Join-Path $dest "LOCAL_STATUS_SUMMARY.md"
  @(
    "# Local Status Summary",
    "",
    "Generated by `scripts/sync-from-local.ps1`.",
    "",
    "Raw local status files such as setup reports, tool status, MCP status, logs, and backups are intentionally not copied because they may contain machine-specific or sensitive details.",
    "",
    "- Source existed: true",
    "- Export timestamp: $($script:Summary.timestamp)"
  ) | Set-Content -LiteralPath $summaryPath -Encoding UTF8
  $script:Summary.filesCopied++
}

function Get-SkillCategory {
  param([string]$SkillName)
  $frontend = @(
    "accessibility-gate","codebase-recon-orchestrator","component-supply-router","design-source-grounding",
    "dynamic-ui-color-contrast-logic","dynamic-ui-spacing-rhythm-logic","dynamic-ui-typography-logic",
    "frontend-design","frontend-inspection-discipline","frontend-tool-orchestrator","layout-composition-fundamentals",
    "library-first-ui-builder","motion-quality-router","performance-triage","project-setup-capability-scan",
    "static-template-client-sites","web-design-guidelines"
  )
  $backend = @(
    "api-contract-orchestrator","backend-database-project-scan","backend-database-tool-orchestrator",
    "backend-observability-debugging","backend-performance-triage","backend-refactor-safety",
    "database-safety-orchestrator","deployment-readiness-gate","migration-backup-restore-gate",
    "security-env-secrets-gate","sql-operations-gate","vps-ssh-operations-gate"
  )
  $pm = @(
    "codebase-knowledge-graph-recon","inefficiency-and-improvement-reviewer","project-manager-execution-ledger",
    "task-bundling-controller","task-roadmap-orchestrator","task-routing-and-skill-selection",
    "verification-gate-controller"
  )

  if ($frontend -contains $SkillName) { return "frontend" }
  if ($backend -contains $SkillName) { return "backend-database" }
  if ($pm -contains $SkillName) { return "project-manager" }
  return "existing-global"
}

function Export-Skills {
  $skillsSource = Join-Path $CodexRoot "skills"
  Remove-GeneratedFolder "skills/frontend"
  Remove-GeneratedFolder "skills/backend-database"
  Remove-GeneratedFolder "skills/project-manager"
  Remove-GeneratedFolder "skills/existing-global"

  if (-not (Test-Path -LiteralPath $skillsSource)) {
    $script:Summary.warnings += "Missing skills source: $skillsSource"
    return
  }

  Get-ChildItem -LiteralPath $skillsSource -Directory -Force | ForEach-Object {
    $skillName = $_.Name
    $category = Get-SkillCategory $skillName
    $dest = Join-Path $RepoRoot ("skills/$category/$skillName")
    Ensure-Dir $dest

    Copy-IfExists (Join-Path $_.FullName "SKILL.md") (Join-Path $dest "SKILL.md")
    Get-ChildItem -LiteralPath $_.FullName -Recurse -File -Force -ErrorAction SilentlyContinue | Where-Object {
      $name = $_.Name
      if ($_.FullName -match "\\node_modules\\|\\.git\\|\\.understand-anything\\|\\.retrieval\\|\\.codegraph\\|\\.ai-task\\") { return $false }
      if ($name -eq "SKILL.md") { return $false }
      return ($_.Extension -in @(".md",".mjs",".js",".sh") -or $name -eq "package.json")
    } | ForEach-Object {
      $relative = Get-SafeRelativePath (Join-Path $skillsSource $skillName) $_.FullName
      Copy-IfExists $_.FullName (Join-Path $dest $relative)
    }
  }
}

function Export-Agents {
  $destination = Join-Path $RepoRoot "AGENTS.md"
  $candidates = @(
    (Join-Path $CodexRoot "AGENTS.md"),
    "C:\Users\acer\Documents\Codex\2026-05-22\create-a-reusable-codex-skill-for\AGENTS.md"
  )
  foreach ($candidate in $candidates) {
    if (Test-Path -LiteralPath $candidate) {
      Copy-Item -LiteralPath $candidate -Destination $destination -Force
      $script:Summary.filesCopied++
      return
    }
  }
}

Export-System "agentic-frontend" (Join-Path $CodexRoot "agentic-frontend") "systems/agentic-frontend"
Export-System "agentic-backend-database" (Join-Path $CodexRoot "agentic-backend-database") "systems/agentic-backend-database"
Export-System "agentic-project-manager" (Join-Path $CodexRoot "agentic-project-manager") "systems/agentic-project-manager"
Export-Skills
Export-Agents

Ensure-Dir (Join-Path $RepoRoot "manifests")
$Summary | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $RepoRoot "manifests/last-sync-summary.json") -Encoding UTF8

& (Join-Path $PSScriptRoot "redact-scan.ps1")
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host "SYNC COMPLETE"
Write-Host "Files copied: $($Summary.filesCopied)"
git -C $RepoRoot status --short
